Results panel was implemented
NastyaKuvi/code-and-magick pull request #2
Opened 2017-12-07 20:01 UTC by NastyaKuvi

2017-12-08 18:45 UTC, oliktva requested changes

2017-12-08 18:45 UTC, oliktva commented on js/stat.js
> +      ctx.fillStyle = 'rgba(0, 0, 255, ' + Math.random(0, 1) + ')';
Math.random() - не принимает аргументы (см. https://goo.gl/7tZxeH). И может выдать 0, тогда мы не увидим результат. Давай это поправим.

2017-12-08 18:45 UTC, oliktva commented on js/stat.js
> +  ctx.fillRect(mainX - 10, 10, 420, 270);
Давай оптимизируемся отрисовку облака. Подумай как это можно сделать.

2017-12-08 18:45 UTC, oliktva commented on js/stat.js
> +  var maxTime = -1;
Поиск максимального тоже можно оптимизировать.

2017-12-08 18:45 UTC, oliktva commented on js/stat.js
> +      ctx.fillStyle = myColumnColor;
Давай сделаем здесь через тернарный оператор.

2017-12-08 18:45 UTC, oliktva commented on js/stat.js
> +    ctx.fillText(names[i], currentX, 270);
Давай добавим отображение времени как на картинке в задании.

2017-12-11 16:51 UTC, oliktva requested changes
Еще немного надо поправить :)

2017-12-11 16:51 UTC, oliktva commented on js/stat.js
> +function paintRectangle(ctx, x, y, w, h, color) {
забегая немного вперед https://learn.javascript.ru/function-declaration-expression#function-expression

2017-12-11 16:51 UTC, oliktva commented on js/stat.js
> +function paintRectangle(ctx, x, y, w, h, color) {
Давай функцию объявлять с помощью Function Expression, чтобы не было лишних ошибок

2017-12-11 16:51 UTC, oliktva commented on js/stat.js
> +  ctx.font = 'PT Mono 16px';
почему это не внести в функцию paintText?

2017-12-11 16:51 UTC, oliktva commented on js/stat.js
> +  var mainHeight = 270;
давай объявление констант, переменных тела функции отделять пустой строкой

2017-12-11 16:51 UTC, oliktva commented on js/stat.js
> +  var histogramHeight = 150;
давай объявление всех переменных вынесем наверх функции

2017-12-11 16:51 UTC, oliktva commented on js/stat.js
> +    var currentColor = names[i] === 'Вы' ?
кусок внутри цикла можно вынести в функцию и тогда не придется делать 
` for (var i = 0; i < times.length; i++) {
     times[i] = Math.round(times[i]);
  }`

2017-12-11 16:51 UTC, oliktva commented on js/stat.js
> +    paintRectangle(ctx, currentX, currentY, columnWidth, currentTime, currentColor);
очень много аргументов, может есть какие-то переменные, которые использует только эта функция и объявить их только там?

2017-12-11 16:51 UTC, oliktva commented on js/stat.js
> +  var columnDist = 50;
и давай сделаем совсем круто, объявим все значения, которые даны у нас в задании как константы https://up.htmlacademy.ru/javascript/9/criteries#basic-4.

2017-12-11 16:51 UTC, oliktva commented on js/stat.js
> +  paintRectangle(ctx, mainX + 10, mainY + 10, mainWidth, mainHeight, 'rgba(0, 0, 0, 0.7)');
отрисовка обычно именуют render (как в твоем методе из задания). Давай переименуем paint в render.

2017-12-11 19:59 UTC, NastyaKuvi commented on js/stat.js
> +  ctx.font = 'PT Mono 16px';
font и baseline, задается 1 раз и не меняется, посчитала что не зачем каждый раз сетить эти значения

2017-12-11 20:11 UTC, NastyaKuvi commented on js/stat.js
> +  var mainHeight = 270;
ОК

2017-12-11 20:11 UTC, NastyaKuvi commented on js/stat.js
> +  paintRectangle(ctx, mainX + 10, mainY + 10, mainWidth, mainHeight, 'rgba(0, 0, 0, 0.7)');
ок

2017-12-11 20:14 UTC, NastyaKuvi commented on js/stat.js
> +  var columnDist = 50;
ок

2017-12-11 20:16 UTC, NastyaKuvi commented on js/stat.js
> +    var currentColor = names[i] === 'Вы' ?
делала потому что максимум не хотел на дробных считаться, а щас считается - магия. ладно уберу этот цикл

2017-12-11 20:17 UTC, NastyaKuvi commented on js/stat.js
> +  var histogramHeight = 150;
ок

2017-12-11 20:19 UTC, NastyaKuvi commented on js/stat.js
> +    paintRectangle(ctx, currentX, currentY, columnWidth, currentTime, currentColor);
в paintText и paintRectangle ничего внести нельзя все объявленные переменные используются минимум два раза

2017-12-11 20:26 UTC, NastyaKuvi commented on js/stat.js
> +function paintRectangle(ctx, x, y, w, h, color) {
ок

2017-12-12 08:33 UTC, oliktva commented on js/stat.js
> +    var currentColor = names[i] === 'Вы' ?
В доке ничего не сказано про целочисленность (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/max) + в js есть только тип number.

2017-12-12 08:47 UTC, oliktva approved these changes
Ок, оставляем так. Но далее надо делать так, чтобы на вход функции было не более 5 аргументов. 

Лирическое отступление: в данном случае это можно было бы сделать разделив логику отрисовки облака и столбца, так как они совершенно не связаны. И менять дальше можно было бы более гибко (заказчик захочет сделать облако круглым, а столбец стрелкой или завитушкой или еще чем-нибудь). Менять сейчас не будем, но прими к сведению.

2017-12-12 09:37 UTC, merged