Similar wizards dialog was implemented
NastyaKuvi/code-and-magick pull request #3
Opened 2017-12-13 19:05 UTC by NastyaKuvi

2017-12-16 11:11 UTC, oliktva requested changes
Совсем чуть-чуть поправить :)

2017-12-16 11:11 UTC, oliktva commented on css/main.css
> +  overflow: hidden;
это же тут необязательно?

2017-12-16 11:11 UTC, oliktva commented on js/setup.js
> +for (var i = 0; i < wizards.length; i++) {
Давай заменим цикл на использование метода forEach https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2017-12-16 13:35 UTC, NastyaKuvi commented on css/main.css
> +  overflow: hidden;
помнишь я говорила что у меня в зависимости от имени расстояния между магами меняются, вот это к этому

2017-12-16 15:02 UTC, oliktva commented on css/main.css
> +  overflow: hidden;
max-width да, коммент про overflow:hidden

2018-01-15 09:12 UTC, oliktva approved these changes
👍

2018-01-15 19:42 UTC, merged